# Generated by Django 6.0.6 on 2026-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/covers/'),
        ),
    ]
